"""embedding model

Revision ID: 3df352d944b3
Revises: 111a50cf1a2c
Create Date: 2026-10-06 09:59:38.480048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3df352d944b3'
down_revision: Union[str, Sequence[str], None] = '111a50cf1a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('needs', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('offers', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'embedding_model')
    op.drop_column('needs', 'embedding_model')
    # ### end Alembic commands ###
