"""initial schema

All Phase 1 tables and indexes, the PostGIS + pgvector extensions, and a trigger
that makes the events table append-only.

Revision ID: 296c647e7776
Revises: 
Create Date: 2026-10-06 09:23:03.008855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '296c647e7776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions must exist before any geography/vector column is created.
    # IF NOT EXISTS: the docker init script may already have enabled them.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('circuits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='proposed', nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'active', 'completed', 'dissolved')", name='ck_circuits_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_circuits_round_id', 'circuits', ['round_id'], unique=False)
    op.create_index('ix_circuits_status_expires', 'circuits', ['status', 'expires_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_actor_created', 'events', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_events_target', 'events', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_events_type_created', 'events', ['type', 'created_at'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('verification_level', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('open_intro_slots', sa.Integer(), server_default='3', nullable=False),
    sa.Column('circuits_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('open_to_cross_sector', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'founder', 'mentor', 'investor', 'partner_admin')", name='ck_members_role'),
    sa.CheckConstraint('open_intro_slots >= 0', name='ck_members_open_intro_slots'),
    sa.CheckConstraint('verification_level BETWEEN 1 AND 4', name='ck_members_verification_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_members_city', 'members', ['city'], unique=False)
    op.create_index('ix_members_location', 'members', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_members_role', 'members', ['role'], unique=False)
    op.create_table('traits',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('circuit_legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('circuit_id', sa.UUID(), nullable=False),
    sa.Column('giver_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('consent', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('fulfilled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("consent IN ('pending', 'accepted', 'declined')", name='ck_circuit_legs_consent'),
    sa.CheckConstraint('giver_id <> receiver_id', name='ck_circuit_legs_not_self'),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 5', name='ck_circuit_legs_rating'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giver_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_id', 'giver_id', name='uq_circuit_legs_circuit_giver')
    )
    op.create_index('ix_circuit_legs_giver_id', 'circuit_legs', ['giver_id'], unique=False)
    op.create_index('ix_circuit_legs_receiver_id', 'circuit_legs', ['receiver_id'], unique=False)
    op.create_table('connections',
    sa.Column('member_a', sa.UUID(), nullable=False),
    sa.Column('member_b', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('mutual', 'event', 'intro')", name='ck_connections_source'),
    sa.CheckConstraint('member_a < member_b', name='ck_connections_ordered'),
    sa.CheckConstraint('strength >= 0 AND strength <= 1', name='ck_connections_strength'),
    sa.ForeignKeyConstraint(['member_a'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_b'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_a', 'member_b')
    )
    op.create_index('ix_connections_member_b', 'connections', ['member_b'], unique=False)
    op.create_table('intro_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_member', sa.UUID(), nullable=False),
    sa.Column('to_member', sa.UUID(), nullable=False),
    sa.Column('via_member', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'expired')", name='ck_intro_requests_status'),
    sa.CheckConstraint('from_member <> to_member', name='ck_intro_requests_not_self'),
    sa.ForeignKeyConstraint(['from_member'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_member'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['via_member'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intro_requests_from_created', 'intro_requests', ['from_member', 'created_at'], unique=False)
    op.create_index('ix_intro_requests_to_status', 'intro_requests', ['to_member', 'status'], unique=False)
    op.create_table('match_results',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('candidate_member_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('local', 'bridge')", name='ck_match_results_source'),
    sa.ForeignKeyConstraint(['candidate_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'candidate_member_id')
    )
    op.create_index('ix_match_results_member_score', 'match_results', ['member_id', sa.literal_column('score DESC')], unique=False)
    op.create_table('member_traits',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'trait_id')
    )
    op.create_index('ix_member_traits_trait_id', 'member_traits', ['trait_id'], unique=False)
    op.create_table('needs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("owner_type IN ('member', 'startup')", name='ck_needs_owner_type'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_needs_capability_id', 'needs', ['capability_id'], unique=False)
    op.create_index('ix_needs_embedding_hnsw', 'needs', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_needs_owner', 'needs', ['owner_type', 'owner_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_capability_id', 'offers', ['capability_id'], unique=False)
    op.create_index('ix_offers_embedding_hnsw', 'offers', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_offers_member_id', 'offers', ['member_id'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_domain', sa.String(length=253), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('hiring', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('open_roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('claimed_by_member_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='seed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('seed', 'crawler', 'user')", name='ck_startups_source'),
    sa.ForeignKeyConstraint(['claimed_by_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_domain')
    )
    op.create_index('ix_startups_hiring', 'startups', ['hiring'], unique=False, postgresql_where=sa.text('hiring'))
    op.create_index('ix_startups_location', 'startups', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_startups_sector', 'startups', ['sector'], unique=False)
    op.create_table('startup_members',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('startup_id', 'member_id')
    )
    op.create_index('ix_startup_members_member_id', 'startup_members', ['member_id'], unique=False)
    op.create_table('startup_traits',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('startup_id', 'trait_id')
    )
    op.create_index('ix_startup_traits_trait_id', 'startup_traits', ['trait_id'], unique=False)
    # ### end Alembic commands ###

    # events is append-only: reject any UPDATE or DELETE at the database level,
    # so no code path (or person with a SQL shell) can rewrite history by accident.
    op.execute("""
        CREATE FUNCTION events_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'events is append-only: % is not allowed', TG_OP;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER events_no_update_delete
        BEFORE UPDATE OR DELETE ON events
        FOR EACH ROW EXECUTE FUNCTION events_append_only()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS events_no_update_delete ON events")
    op.execute("DROP FUNCTION IF EXISTS events_append_only()")
    # Extensions are left installed: other database objects may depend on them.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_startup_traits_trait_id', table_name='startup_traits')
    op.drop_table('startup_traits')
    op.drop_index('ix_startup_members_member_id', table_name='startup_members')
    op.drop_table('startup_members')
    op.drop_index('ix_startups_sector', table_name='startups')
    op.drop_index('ix_startups_location', table_name='startups', postgresql_using='gist')
    op.drop_index('ix_startups_hiring', table_name='startups', postgresql_where=sa.text('hiring'))
    op.drop_table('startups')
    op.drop_index('ix_offers_member_id', table_name='offers')
    op.drop_index('ix_offers_embedding_hnsw', table_name='offers', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_offers_capability_id', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_needs_owner', table_name='needs')
    op.drop_index('ix_needs_embedding_hnsw', table_name='needs', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_needs_capability_id', table_name='needs')
    op.drop_table('needs')
    op.drop_index('ix_member_traits_trait_id', table_name='member_traits')
    op.drop_table('member_traits')
    op.drop_index('ix_match_results_member_score', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_intro_requests_to_status', table_name='intro_requests')
    op.drop_index('ix_intro_requests_from_created', table_name='intro_requests')
    op.drop_table('intro_requests')
    op.drop_index('ix_connections_member_b', table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_circuit_legs_receiver_id', table_name='circuit_legs')
    op.drop_index('ix_circuit_legs_giver_id', table_name='circuit_legs')
    op.drop_table('circuit_legs')
    op.drop_table('traits')
    op.drop_index('ix_members_role', table_name='members')
    op.drop_index('ix_members_location', table_name='members', postgresql_using='gist')
    op.drop_index('ix_members_city', table_name='members')
    op.drop_table('members')
    op.drop_index('ix_events_type_created', table_name='events')
    op.drop_index('ix_events_target', table_name='events')
    op.drop_index('ix_events_actor_created', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_circuits_status_expires', table_name='circuits')
    op.drop_index('ix_circuits_round_id', table_name='circuits')
    op.drop_table('circuits')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
