"""intro outcomes

Intro requests get a response note, the match that led to them, outcome ratings,
a "cancelled" status, and a rule allowing one pending request per pair.
(CHECK constraints are written by hand: autogenerate does not detect them.)

Revision ID: d3dfe49e7b0d
Revises: 3df352d944b3
Create Date: 2026-10-06 10:26:24.753926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd3dfe49e7b0d'
down_revision: Union[str, Sequence[str], None] = '3df352d944b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intro_requests', sa.Column('response_note', sa.Text(), nullable=True))
    op.add_column('intro_requests', sa.Column('match_source', sa.String(length=10), nullable=True))
    op.add_column('intro_requests', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('intro_requests', sa.Column('from_rating', sa.SmallInteger(), nullable=True))
    op.add_column('intro_requests', sa.Column('to_rating', sa.SmallInteger(), nullable=True))
    op.create_index('uq_intro_requests_one_pending', 'intro_requests', ['from_member', 'to_member'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###

    op.drop_constraint('ck_intro_requests_status', 'intro_requests', type_='check')
    op.create_check_constraint('ck_intro_requests_status', 'intro_requests',
                               "status IN ('pending', 'accepted', 'declined', 'expired', 'cancelled')")
    op.create_check_constraint('ck_intro_requests_match_source', 'intro_requests',
                               "match_source IN ('local', 'bridge')")
    op.create_check_constraint('ck_intro_requests_from_rating', 'intro_requests',
                               'from_rating IS NULL OR from_rating BETWEEN 1 AND 5')
    op.create_check_constraint('ck_intro_requests_to_rating', 'intro_requests',
                               'to_rating IS NULL OR to_rating BETWEEN 1 AND 5')


def downgrade() -> None:
    """Downgrade schema."""
    for name in ('ck_intro_requests_to_rating', 'ck_intro_requests_from_rating', 'ck_intro_requests_match_source'):
        op.drop_constraint(name, 'intro_requests', type_='check')
    op.execute("UPDATE intro_requests SET status = 'expired' WHERE status = 'cancelled'")
    op.drop_constraint('ck_intro_requests_status', 'intro_requests', type_='check')
    op.create_check_constraint('ck_intro_requests_status', 'intro_requests',
                               "status IN ('pending', 'accepted', 'declined', 'expired')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_intro_requests_one_pending', table_name='intro_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_column('intro_requests', 'to_rating')
    op.drop_column('intro_requests', 'from_rating')
    op.drop_column('intro_requests', 'match_score')
    op.drop_column('intro_requests', 'match_source')
    op.drop_column('intro_requests', 'response_note')
    # ### end Alembic commands ###
