"""member auth subject

Revision ID: 111a50cf1a2c
Revises: 13f773441341
Create Date: 2026-10-06 09:48:09.594666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '111a50cf1a2c'
down_revision: Union[str, Sequence[str], None] = '13f773441341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('auth_subject', sa.String(length=255), nullable=True))
    op.create_index('uq_members_auth_subject', 'members', ['auth_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_members_auth_subject', table_name='members')
    op.drop_column('members', 'auth_subject')
    # ### end Alembic commands ###
